[workspace]
resolver = "3"
members = [
  "monitoring-core",
]

[workspace.dependencies]
aws-iot-device-sdk-rust = "0.6.0"
chrono = "0.4.41"
dotenvy = "0.15.7"
prost = "0.14"
rand = "0.9.2"
rumqttc = "0.24.0"
tokio = "1.47.1"