version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    # volumes:
      # - mosquitto_data:/mosquitto/data
      # - mosquitto_log:/mosquitto/log
      # - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
# volumes:
#   mosquitto_data:
#   mosquitto_log: